name: inception

secrets:
  mysql_password:
    file: ../secrets/mysql_password.txt
  mysql_root_password:
    file: ../secrets/mysql_root_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
  ftp_user_password:
    file: ../secrets/ftp_user_password.txt

volumes:
  wordpress:
    driver: local
    driver_opts:
      device: "${DEVICE_PATH}/wordpress"
      o: bind
      type: none
  mariadb:
    driver: local
    driver_opts:
      device: "${DEVICE_PATH}/mariadb"
      o: bind
      type: none
  rsyslog:
    driver: local
    driver_opts:
      device: "${DEVICE_PATH}/rsyslog"
      o: bind
      type: none

networks:
  inception:
    name: inception
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://10.5.0.10:514"
        tag: nginx
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    depends_on:
      rsyslog:
        condition: service_healthy
      wordpress:
        condition: service_started
      adminer:
        condition: service_started
      lighttpd:
        condition: service_started
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://10.5.0.10:514"
        tag: wordpress
    secrets:
      - mysql_password
      - mysql_root_password
      - wp_admin_password
      - wp_user_password
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    depends_on:
      rsyslog:
        condition: service_healthy
      mariadb:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - inception
    restart: unless-stopped

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://10.5.0.10:514"
        tag: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    depends_on:
      rsyslog:
        condition: service_healthy
    secrets:
      - mysql_password
      - mysql_root_password
    env_file:
      - .env
    networks:
      - inception
    restart: unless-stopped

  redis:
    container_name: redis
    build: ./requirements/redis
    depends_on:
      rsyslog:
        condition: service_healthy
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://10.5.0.10:514"
        tag: redis
    env_file:
      - .env
    networks:
      - inception
    restart: unless-stopped

  lighttpd:
    container_name: lighttpd
    build: ./requirements/lighttpd
    depends_on:
      rsyslog:
        condition: service_healthy
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://10.5.0.10:514"
        tag: lighttpd
    env_file:
      - .env
    networks:
      - inception
    restart: unless-stopped

  ftp:
    container_name: ftp
    build: ./requirements/ftp
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://10.5.0.10:514"
        tag: ftp
    ports:
      - "21:21"
      - "30000-30005:30000-30005"
    volumes:
      - wordpress:/var/www/html
    depends_on:
      rsyslog:
        condition: service_healthy
      wordpress:
        condition: service_started
    env_file:
      - .env
    secrets:
    - ftp_user_password
    networks:
      - inception
    stop_grace_period: 1s
    restart: unless-stopped

  adminer:
    container_name: adminer
    build: ./requirements/adminer/
    depends_on:
      rsyslog:
        condition: service_healthy
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://10.5.0.10:514"
        tag: adminer
    networks:
      - inception
    restart: unless-stopped

  rsyslog:
    container_name: rsyslog
    build: ./requirements/rsyslog/
    volumes:
      - rsyslog:/var/log/centralized
    networks:
      inception:
        ipv4_address: 10.5.0.10
    healthcheck:
      test: ["CMD", "nc", "-vz", "-w", "2", "localhost", "514"]
      interval: 2s
      timeout: 2s
      retries: 3
      start_period: 2s
    restart: unless-stopped
