username = "jwuille"

Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine319"
  config.ssh.forward_agent = true
  config.vm.hostname = "inception"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
    vb.name = "inception-vm"
  end

  config.vm.network "private_network", ip: "192.168.56.10"
  config.vm.network "forwarded_port", guest: 543, host: 8543

  config.vm.synced_folder ".", "/vagrant", type: "rsync"

  # --- Provisioning : creating user ---
  config.vm.provision "shell", env: {"USERNAME" => username }, inline: <<-SHELL
    set -e

    # Packages
    apk update
    apk add docker docker-compose docker-cli-compose make git curl sudo bash firefox-esr xauth
    
    # Graphic issues
    sudo apk add mesa-gl mesa-egl pciutils-libs libcanberra libcanberra-gtk3

    # Fonts
    apk add font-noto font-noto-cjk font-noto-emoji ttf-dejavu fontconfig

    # Create User
    if ! id $USERNAME >/dev/null 2>&1; then
      adduser -D -s /bin/bash $USERNAME
      echo "$USERNAME:$USERNAME" | chpasswd
    fi

    # Add groups
    adduser $USERNAME docker
    adduser $USERNAME wheel 2>/dev/null || true

    # Sudo no password
    echo "$USERNAME ALL=(ALL) NOPASSWD: ALL" > "/etc/sudoers.d/$USERNAME"
    chmod 440 "/etc/sudoers.d/$USERNAME"
    
    # Docker boot
    rc-update add docker boot
    service docker start || true

    # # /etc/hosts
    sed -i "s/localhost /localhost ${USERNAME}.42.fr /g" /etc/hosts

    # SSH X11 forwarding
    sed -i '/^X11Forwarding/d; /^#X11Forwarding/d' /etc/ssh/sshd_config
    echo 'X11Forwarding yes' >> /etc/ssh/sshd_config

    sed -i '/^X11UseLocalhost/d; /^#X11UseLocalhost/d' /etc/ssh/sshd_config
    echo 'X11UseLocalhost no' >> /etc/ssh/sshd_config

    rc-service sshd restart
    
    # Copie key SSH of vagrant to $USERNAME (for allowing Vagrant to connect)
    mkdir -p "/home/$USERNAME/.ssh"
    cp /home/vagrant/.ssh/authorized_keys "/home/$USERNAME/.ssh/authorized_keys"
    chown -R "$USERNAME:$USERNAME" "/home/$USERNAME/.ssh"
    chmod 700 "/home/$USERNAME/.ssh"
    chmod 600 "/home/$USERNAME/.ssh/authorized_keys"
  SHELL

  # --- tell Vagrant to use $USERNAME for SSH ---
  # config.ssh.username = username
end

