template(name="dynatemplate" type="string"
  string="/var/log/centralized/%programname%.log")
module(load="imtcp") # needs to be done just once
input(type="imtcp" port="514")

action(type="omfile" dynaFile="dynatemplate")
