[www]
user  = adminer
group = adminer

listen = 8080
listen.owner = adminer
listen.group = adminer

; PHP-FPM create workers automatically and destruct them
pm                   = dynamic
pm.max_children      = 5
pm.start_servers     = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3
